Auxiliar_Ensino/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('perfil/', include('perfil.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('prova/', include('prova.urls')),
    path('amigos/', include('amigos.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#TODO Colocar a imagem Padrão na pasta

amigos/urls.py
from django.urls import path

from amigos.views import MandarSolicitacao

app_name = 'amigo'

urlpatterns = [
    path('adiciona/<int:pk>', MandarSolicitacao.as_view(), name='mandar_solicitacao'),
    # path('remover/<int:pk>', RemoverAmigo.as_view(), name='remover_amigo')
]

perfil/urls.py
from django.urls import path, include
from .views import LogOut, PerfilUsuario, SignIn, LogIn

app_name = 'perfil'

urlpatterns = [
    path('login', LogIn.as_view(),name='login'),
    path('logout', LogOut.as_view(), name='logout'),
    path('signin', SignIn.as_view(), name='signin'),
    path('<str:slug>', PerfilUsuario.as_view(), name='perfil_detalhe'),
    
]

prova/urls.py
from django.urls import path
from .views import ProvaDeletar, ProvaEdit, ProvaDetalhe, ProvaCriar

app_name = 'prova'

urlpatterns = [
    path('detalhe/<str:slug>', ProvaDetalhe.as_view(), name='prova_detalhe'),
    path('criar', ProvaCriar.as_view(), name='prova_criar'),
    path('edit/<str:slug>', ProvaEdit.as_view(), name='prova_edit'),
    path('deletar/<int:pk>', ProvaDeletar.as_view(), name='prova_deletar')
]

perfil/models.py
from django.db import models
from django.contrib.auth.models import User
from especializacao.models import Especializacao
from django.utils import timezone

# Create your models here.

class Perfil(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=100)
    email = models.EmailField()
    especializacao = models.ForeignKey(Especializacao, on_delete=models.DO_NOTHING, default=2)
    data_criacao = models.DateTimeField(default=timezone.now)
    foto_perfil = models.ImageField(upload_to='perfil/%Y/%m', blank=True, null=True)
    slug = models.SlugField(default=None)

    def __str__(self):
        return f'{self.nome} {self.sobrenome}' or self.usuario
    
    def save(self):
        if not self.slug:
            self.slug=self.usuario

        return super().save()

perfil/forms.py
from django import forms
from . models import Perfil
from django.contrib.auth.models import User


class FormUsuario(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Usuário'
        self.fields['first_name'].label = 'Nome'
        self.fields['last_name'].label = 'Sobrenome'
        self.fields['password'].label = 'Senha'
        self.fields['email'].label = 'E-Mail'
        
    def clean(self):
        data = self.cleaned_data
        usuario = data.get('username')
        nome = data.get('first_name')
        sobrenome = data.get('last_name')
        senha = data.get('password')
        email = data.get('email')
        
        if not email:
            self.add_error(
                'email',
                'Você precisa cadastrar um email'
            )
 
        
    class Meta:
        model = User
        widgets = {
            'password': forms.PasswordInput(attrs={
                'id': 'senha_cadastro'
            })
        }
        fields = ('username', 'first_name', 'last_name', 'email', 'password')
        

        

perfil/views.py
from typing import List
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic import FormView

from amigos.models import ListaAmigos
from .models import Perfil
from .forms import FormUsuario
from prova.models import Prova
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class SignIn(FormView):
    template_name = 'perfil/signin.html'
    form_class = FormUsuario
    
    def form_valid(self, form):
        cadastro_usuario = form.cleaned_data
        
        user = User.objects.create_user(
            username=cadastro_usuario['username'], 
            email=cadastro_usuario['email'], 
            password=cadastro_usuario['password'],
            first_name=cadastro_usuario['first_name'], 
            last_name=cadastro_usuario['last_name']
        )
        
        user.save()
        
        perfil = Perfil.objects.create(
            usuario=user,
            email=cadastro_usuario['email'], 
            nome=cadastro_usuario['first_name'], 
            sobrenome=cadastro_usuario['last_name']
        )
        
        perfil.save()
        
        return redirect('perfil:login')
    
class LogIn(LoginView):
    template_name = 'perfil/login.html'
    next_page = 'dashboard:index'
    
class LogOut(LogoutView):
    pass

class PerfilUsuario(DetailView):
    template_name = 'perfil/perfil_index.html'
    model = Perfil
    context_object_name = 'perfil'


    def get_context_data(self, **kwargs):
        contexto = super().get_context_data(**kwargs)
        perfil = self.get_object()
        lista_amigos = ListaAmigos.objects.get(user=perfil.usuario_id)
        contexto['perfil'] = perfil
        contexto['lista_amigos'] = lista_amigos
        

        return contexto

  
    

perfil/templates/perfil/login.html
{% extends 'base.html' %}

{% block 'conteudo' %}
<h1>LOG IN</h1>
<form method='POST' action="{% url 'perfil:login' %}">
    {% csrf_token %} 
    <table>
    {{ form }}
    <tr>
        <td>
            <input type='submit' value="Enviar">
        </td>
    </tr>
    </table>
</form>

{% endblock %}

perfil/templates/perfil/perfil_index.html
{% extends 'base.html' %}

{% block 'conteudo' %}

    {% if perfil.foto_perfil %}
        <p>
            {{ perfil.foto_perfil.url }}
        </p>
    {% endif %}

    <h1>{{ perfil.nome }} {{ perfil.sobrenome }}</h1>

    {% if perfil.usuario_id != user.id %}

        {% if perfil.usuario_id in lista_amigos.friends%}

            <h3>Já são Amigos</h3>

            <button type='button' value='Desfazer Amizade' method='POST'>
                <a href="#">Desfazer Amizade</a>
            </button>
        
        {% else %}

            <button type='button' value='Adicionar Amigo' method='POST'>
                <a href="{% url 'amigo:mandar_solicitacao' perfil.id %}">Adicionar Amigo</a>
            </button>

        {% endif %}  

    {% endif %}


{% endblock %}

perfil/templates/perfil/signin.html
{% extends 'base.html' %}

{% block 'conteudo' %}
<h1>SIGN IN</h1>
<form method='POST' action="{% url 'perfil:signin' %}">
    {% csrf_token %} 
    <table>
    {{ form }}
    <tr>
        <td>
            <input type='submit' value="Enviar">
        </td>
    </tr>
    </table>
</form>

{% endblock %}