Auxiliar_Ensino/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('perfil/', include('perfil.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('prova/', include('prova.urls')),
    path('amigos/', include('amigos.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#TODO Colocar a imagem Padrão na pasta

dashboard/urls.py
from django.urls import path
from .views import Index,Provas

app_name = 'dashboard'

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('provas', Provas.as_view(), name='provas'),

]

perfil/urls.py
from django.urls import path, include
from .views import LogOut, PerfilUsuario, SignIn, LogIn

app_name = 'perfil'

urlpatterns = [
    path('login', LogIn.as_view(),name='login'),
    path('logout', LogOut.as_view(), name='logout'),
    path('signin', SignIn.as_view(), name='signin'),
    path('<str:slug>', PerfilUsuario.as_view(), name='perfil_detalhe'),
    
]

prova/urls.py
from django.urls import path
from .views import ProvaDeletar, ProvaEdit, ProvaDetalhe, ProvaCriar

app_name = 'prova'

urlpatterns = [
    path('detalhe/<str:slug>', ProvaDetalhe.as_view(), name='prova_detalhe'),
    path('criar', ProvaCriar.as_view(), name='prova_criar'),
    path('edit/<str:slug>', ProvaEdit.as_view(), name='prova_edit'),
    path('deletar/<int:pk>', ProvaDeletar.as_view(), name='prova_deletar')
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from perfil.models import Perfil
from prova.models import Prova
from django.db.models import Q

#TODO Criar SideBar da Dashboard


# Create your views here.

class Index(LoginRequiredMixin, ListView):
    template_name = 'dashboard/dashboard.html'
    model = Perfil
    context_object_name = 'perfil'
    redirect_field_name = 'perfil:login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        perfil = Perfil.objects.get(usuario_id=self.request.user.id)
        provas = Prova.objects.filter(perfil_autor_id=perfil.id)
        print(perfil)
        context["perfil"] = perfil
        context["provas"] = provas
        return context
    

class Provas(Index):
    extra_context = {
        'provas': Prova.objects.all()
    }
    
    def get_queryset(self):
        query_set = Prova.objects.filter(perfil_autor_id=self.request.user.id)
        return query_set

dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block 'conteudo' %}
    {% if perfil.foto_perfil %}
        <img src="{{ perfil.foto_perfil.url }}" alt='Esta é a imagem'>

    {% endif %}

    {% if perfil.nome %}
        <h1>Olá {{ perfil.nome }} {{ perfil.sobrenome }}</h1>

    {% else %}
        <h1>Olá {{ perfil.usuario }}</h1>
    {% endif %}


    <button type='button'>
        <a href={% url 'perfil:perfil_detalhe' perfil.slug %}>Ver Perfil</a>
    </button>

    <button type='button'>
        <a href={% url 'prova:prova_criar' %}>Criar Prova</a>
    </button>

    {% block 'dashboard' %}

        {% for prova in provas %}
            <a href="{% url 'prova:prova_detalhe' prova.slug %}">
                {{prova.nome_prova}} {{prova.serie}}
            </a>
        {% endfor %}
    
    {% endblock %}

{% endblock %}

dashboard/templates/dashboard/prova_detalhe.html
{% extends 'dashboard/dashboard.html' %}

{% block 'dashboard' %}

    <button type='button' value='Editar Prova'>
        <a href="{% url 'prova:prova_edit' prova.slug%}">Editar Prova</a>
    </button>

    <h1>{{ prova.nome_prova }}</h1> <h4>{{ prova.note }}</h4>
    <h3>{{ prova.serie }}</h3>

    {{ prova.teste_texto|safe }}
    

{% endblock %}